/* Warning, this file is autogenerated. Don't modify this manually. */
#ifndef SIGSTORE_RS_BINDINGS_H
#define SIGSTORE_RS_BINDINGS_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/// C-compatible algorithm details structure.
///
/// This struct matches the Rust `AlgorithmDetails` but uses C-compatible types.
/// All strings are null-terminated C strings. The caller is responsible for
/// freeing all string pointers using the corresponding free functions.
typedef struct {
    /// The protobuf PublicKeyDetails enum value
    uint32_t known_algorithm;
    /// The public key type (0=RSA, 1=ECDSA, 2=ED25519, 3=PQC)
    uint32_t key_type;
    /// The hash algorithm used (as a u32 representing crypto::Hash)
    uint32_t hash_type;
    /// The protobuf HashAlgorithm enum value
    uint32_t proto_hash_type;
    /// Extra key parameters (e.g., curve name, key size) as null-terminated C string
    /// NULL if not applicable
    char* extra_key_params;
    /// Flag value for CLI usage (e.g., "ecdsa-p256-sha256", "ml-dsa-65") as null-terminated C string
    char* flag_value;
} AlgorithmDetailsFFI;

/// Get algorithm details for a given PublicKeyDetails enum value.
///
/// # Safety
/// This function is unsafe because it returns a raw pointer. The caller must
/// call `free_algorithm_details_ffi` to free the returned pointer.
///
/// # Arguments
/// * `algorithm` - The protobuf PublicKeyDetails enum value (as u32)
///
/// # Returns
/// * A pointer to `AlgorithmDetailsFFI` on success, or null on error
AlgorithmDetailsFFI* get_algorithm_details_ffi(uint32_t algorithm);

/// Get algorithm details from public key bytes by detecting the key type.
///
/// # Safety
/// This function is unsafe because it takes a raw pointer and returns a raw pointer.
/// The caller must:
/// - Ensure `pub_key_bytes` points to a valid buffer of at least `len` bytes
/// - Call `free_algorithm_details_ffi` to free the returned pointer
///
/// # Arguments
/// * `pub_key_bytes` - Pointer to raw public key bytes (DER-encoded or raw format)
/// * `len` - Length of the public key bytes buffer
///
/// # Returns
/// * A pointer to `AlgorithmDetailsFFI` on success, or null on error
AlgorithmDetailsFFI* get_default_algorithm_details_ffi(const uint8_t* pub_key_bytes, size_t len);

/// Free an AlgorithmDetailsFFI structure allocated by the FFI functions.
///
/// # Safety
/// This function is unsafe because it takes a raw pointer. The caller must:
/// - Only call this with a pointer returned by `get_algorithm_details_ffi` or
///   `get_default_algorithm_details_ffi`
/// - Not call this function more than once with the same pointer
/// - Not use the pointer after calling this function
///
/// # Arguments
/// * `details` - Pointer to AlgorithmDetailsFFI to free (can be null)
void free_algorithm_details_ffi(AlgorithmDetailsFFI* details);

#ifdef __cplusplus
}
#endif

#endif /* SIGSTORE_RS_BINDINGS_H */

